### ISSUE TITLE
Error: "The operation completed successfully"

### ISSUE THREAD

**Issue by lf-** [sindresorhus/win-clipboard#16]
I put version 1.0.1 in a pathed folder, ran it from within WSL, and the following happened:

```[lf@Calculon ~]$ RUST_BACKTRACE=1 clipboard.exe --paste
thread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: "The operation completed successfully." } }', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.```

**Comment by sindresorhus** [comment]
@floatdrop We could try to upgrade to the latest version of https://github.com/DoumanAsh/clipboard-win Seems it has a couple of fixes.

**Comment by ledenis** [comment]
I'm also experiencing the issue via clipboardy.

To reproduce:
1. copy a file with Windows
2. try to `--paste`:

```
$ RUST_BACKTRACE=1 ./clipboard.exe --paste
thread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: "L’opération a réussi." } }', src\libcore\result.rs:906:4
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic
   3: std::panicking::begin_panic_fmt
   4: core::panicking::panic_fmt
   5: core::result::unwrap_failed
   6: clipboard::main
   7: main
   8: _tmainCRTStartup
   9: mainCRTStartup
  10: unit_addrs_search
```

I am using :
* Git bash on Windows 10 1903 18362.476
* clipboard v1.0.1 binary (64 bit) from https://github.com/sindresorhus/win-clipboard/releases

@sindresorhus

**Comment by lmoroz** [comment]
Hi
I have same issue with clipboardy on Windows 8 :

>  App [clipboard-client:0] online
 { Error: Command failed: c:\dev\node.js\clipboard\node_modules\clipboardy\fallbacks\windows\clipboard_x86_64.exe --paste
 thread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: "Операция успешно завершена." } }', src\libcore\result.rs:906:4
 note: Run with `RUST_BACKTRACE=1` for a backtrace.
     at makeError (c:\dev\node.js\clipboard\node_modules\clipboardy\node_modules\execa\index.js:174:9)
     at Function.module.exports.sync (c:\dev\node.js\clipboard\node_modules\clipboardy\node_modules\execa\index.js:338:15)
     at Object.pasteSync (c:\dev\node.js\clipboard\node_modules\clipboardy\lib\windows.js:15:30)
     at Object.exports.readSync (c:\dev\node.js\clipboard\node_modules\clipboardy\index.js:42:38)
     at Object.<anonymous> (c:\dev\node.js\clipboard\client.js:6:27)


@sindresorhus

**Comment by ghenania** [comment]
> @floatdrop We could try to upgrade to the latest version of https://github.com/DoumanAsh/clipboard-win Seems it has a couple of fixes.

Any news on this upgrade?

**Comment by loudoweb** [comment]
This upgrade would be awesome!

**Comment by futurGH** [comment]
Would appreciate an update on this!
